### ISSUE TITLE
Find a way to properly test against AD

### ISSUE THREAD

**Issue by tlater-famedly** [famedly/famedly-sync#15]
The underlying cause of #14 is that we have no way to test AD behavior, and LDAP implementations kind of don't like to agree on how to behave. Given that AD is what the tool will most commonly run against, that's a massive oversight.

@skomski has previously suggested https://hub.docker.com/r/dperson/samba/, which might help, though it doesn't map exactly to AD.

**Comment by tlater-famedly** [comment]
@nikzen set up a temporary server that allows us to test during development for the moment.

It would still be great if we could find a way to get an AD server in CI, though.

**Comment by nikzen** [comment]
I will close this issue as setting up an AD in CI is out of scope at the moment
