### ISSUE TITLE
Encoding library that preserves alphabetical order

### ISSUE THREAD

**Issue by jannden** [famedly/famedly-sync#87]
Investigate and find an encoding library that preserves alphabetical order.
If such library was found, implement it.
Start with:  https://github.com/hsivonen/encoding_rs

From [here](https://github.com/famedly/famedly-sync/pull/79#discussion_r1830209026):
> Since base64 would prevent us from ever using source APIs to sort incoming users instead of doing it on the application end, incurring pointless memory overhead, we should not use base64 encoding to do this, but instead an encoding scheme that does preserve alphabetical order. I'm not aware of any off the top of my head, but I am sure they exist. In the short term this is not essential, as we could migrate to a different encoding in the future, but we might as well pick a future proof encoding at this point.

**Comment by emgrav** [comment]
> encoding_rs

Is this the right crate for this? I think we want to use something like `base32hex`, one crate that provides an implementation of this is https://docs.rs/data-encoding/latest/data_encoding/index.html

**Comment by jannden** [comment]
@emgrav Yup, I believe you are pointing to the right direction.
I am wondering though why not to use just a simple `hex` encoding where we won't have to worry about padding.
I will create a WIP and do some tests to see how it works.
