### ISSUE TITLE
Migration executable for encoding old IDs

### ISSUE THREAD

**Issue by jannden** [famedly/famedly-sync#88]
Write migration command for deployed instances of ldap-sync
- in Zitadel, currently the ids are either not encoded or base64 encoded, so we need to go through every instance and appropriately re-encode it in the new way
- this should be created as a secondary entry point with different binary within ldap-sync

More info [here](https://github.com/famedly/famedly-sync/pull/79#discussion_r1830209026).

**Comment by herr-rodrigo** [comment]
Pending on LDAP sync
